language: java
jdk:
  - openjdk8
  - openjdk11
branches:
  only:
    - master
    - develop
    - ci
script: "mvn clean compile"
after_success:
  - >-
    mvn clean test jacoco:report coveralls:report
    --batch-mode --quiet
    -Dmaven.test.skip=false
